@if ($currentitem && $currentitem->id==App\Models\Page::HOME_PAGE_ID)
    @include('backend.pages.partials.home')
@elseif ($currentitem && $currentitem->id==App\Models\Page::ABOUT_US_PAGE_ID)
    @include('backend.pages.partials.about-us')
@elseif ($currentitem && $currentitem->id==App\Models\Page::HELP_PAGE_ID)
    @include('backend.pages.partials.help')
@elseif ($currentitem && $currentitem->name=='student/register')
    @include('backend.pages.partials.student-register')
@elseif ($currentitem && $currentitem->name=='instructor/register')
    @include('backend.pages.partials.instructor-register')
@elseif ($currentitem && $currentitem->name=='instructor/invite-instructor')
    @include('backend.pages.partials.invite-instructor')
@elseif ($currentitem && $currentitem->name=='instructor/dashboard')
    @include('backend.pages.partials.instructor-dashboard')
@elseif ($currentitem && $currentitem->name=='student/dashboard')
    @include('backend.pages.partials.student-dashboard')
@elseif ($currentitem && $currentitem->name=='profile/edit')
    @include('backend.pages.partials.profile-edit')
@endif